
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.40, 0.30], [0.40, -0.30], [-0.40, 0.30], [-0.40, -0.30]]
inflation_radius: 0.55

observation_sources: front_laser_scan rear_laser_scan

front_laser_scan: {sensor_frame: front_laser, data_type: LaserScan, topic: /front/scan, marking: true, clearing: true}
rear_laser_scan: {sensor_frame: rear_laser, data_type: LaserScan, topic: /rear/scan, marking: true, clearing: true}

