manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
lift_column:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.01
  goal_orientation_tolerance: 0.1
