controller_list:
  - name: iiwa/iiwa_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: /ewellix_tlt_node/test_server
    action_ns: single_joint_position
    default: True
    type: SingleJointPosition
    joints:
      - ewellix_lift_top_joint
